# Generated by Django 3.2 on 2021-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalBtc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.CharField(max_length=16, verbose_name='user telegram id')),
                ('buy', models.BooleanField(default=False)),
                ('is_count', models.BooleanField(default=False)),
                ('count', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
