# Generated by Django 3.2 on 2021-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='exchange point')),
                ('stocks', models.FloatField(default=0, verbose_name='how much is in stock')),
                ('sells', models.FloatField(default=0, verbose_name='how much can sell')),
            ],
        ),
        migrations.AddField(
            model_name='proposalbtc',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalbtc',
            name='point_name',
            field=models.CharField(default='', max_length=16, verbose_name='exchange point'),
        ),
    ]
