# Generated by Django 3.2 on 2021-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20210407_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbtc',
            name='point_name',
            field=models.CharField(blank=True, max_length=16, verbose_name='exchange point'),
        ),
    ]
