# Generated by Django 3.2 on 2021-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_proposalbtc_is_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbtc',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposalbtc',
            name='point_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='exchange point'),
        ),
    ]
