# Generated by Django 3.2 on 2021-04-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20210407_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangepoint',
            options={'verbose_name': 'exchange point', 'verbose_name_plural': 'exchange points'},
        ),
        migrations.AlterModelOptions(
            name='proposalbtc',
            options={'verbose_name': 'exchange request', 'verbose_name_plural': 'exchange requests'},
        ),
        migrations.AddField(
            model_name='exchangepoint',
            name='percent_buy',
            field=models.FloatField(default=0, verbose_name='percent buy'),
        ),
        migrations.AddField(
            model_name='exchangepoint',
            name='percent_sell',
            field=models.FloatField(default=0, verbose_name='percent sell'),
        ),
    ]
