# Generated by Django 3.2 on 2021-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20210407_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbtc',
            name='is_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalbtc',
            name='user_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='user phone number'),
        ),
    ]
