# Generated by Django 3.2 on 2021-04-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20210407_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbtc',
            name='date_visit',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='date of visit'),
        ),
    ]
