# Generated by Django 3.2 on 2021-04-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_proposalbtc_date_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepoint',
            name='percent_buy',
        ),
        migrations.RemoveField(
            model_name='exchangepoint',
            name='percent_sell',
        ),
    ]
