# Generated by Django 3.2 on 2021-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20210407_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbtc',
            name='is_visit',
            field=models.BooleanField(default=False),
        ),
    ]
