# Generated by Django 3.2 on 2021-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_rename_is_visit_proposalbtc_is_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbtc',
            name='is_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalbtc',
            name='time_visit',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='time of visit'),
        ),
    ]
